#mqtt:
#  producers:
#    producer-test-01:
#      url: [ tcp://10.190.51.113:1883 ]
#      topics: [ consumer/* ]
#      qos: [ 1 ]
#      async: true
#      client-id: producer-test-01
#  consumers:
#    consumer-test-01:
#      url: [ tcp://10.190.51.113:1883 ]
#      topics: [ consumer/* ]
#      qos: [ 1 ]
#      async: true
#      client-id: consumer-test-01
spring:
  mqtt:
    username:
    password:
    url: tcp://10.190.49.234:1883
    clientId: clientId
    topic: MTN
    completionTimeout: 2000

encrypt:
  cipher-transforms: AES/CBC/PKCS7Padding
  encrypt-type: AES
  encrypt-iv: "0000000000000000"
  encrypt-key: "10293847561029384756102938475600"
