CREATE TABLE IF NOT EXISTS validation_rule
(
    id              bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    rule_type       VARCHAR(255) NOT NULL,
    pojo_name       VARCHAR(255) NOT NULL,
    field_name      VARCHAR(255) NOT NULL,
    validation_rule VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);