study:
  validation:
    rules:
      - pojoName: "User"
        fieldName: "userName"
        validationRule: "javax.validation.constraints.NotBlank"

      - pojoName: "User"
        fieldName: "age"
        validationRule: "javax.validation.constraints.Min(18)"